### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by marios-pz** [marios-pz/nvim#1]
- [x] Remove null-ls
- [ ] Find a better python lsp/linter/formatter
- [x] Apply Best Practices on lazy.nvim
- [ ] Enable Dap only when being used
- [x] Clean out plugins I don't use anymore
- [x] Get rid of treesitter
- [ ] ...

**Comment by marios-pz** [comment]
and update the README ffs
